# Generated by Django 4.2.28 on 2026-03-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("group", models.CharField(blank=True, max_length=50, null=True)),
                ("attendance", models.FloatField(help_text="0-100")),
                ("homework", models.FloatField(help_text="0-100")),
                ("midterm", models.FloatField(help_text="0-100")),
                ("final", models.FloatField(help_text="0-100")),
                (
                    "actual_performance",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Жоғары", "Жоғары"),
                            ("Орташа", "Орташа"),
                            ("Төмен", "Төмен"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "predicted_performance",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Жоғары", "Жоғары"),
                            ("Орташа", "Орташа"),
                            ("Төмен", "Төмен"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
