# Generated by Django 4.2.28 on 2026-03-03 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_quiz_submission_question_choice_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="topic",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="quiz",
            name="parent_quiz",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="remedials",
                to="students.quiz",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="quiz_type",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("ai", "AI Generated"),
                    ("remedial", "Remedial"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="subject",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="quiz",
            name="target_student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_quizzes",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="topic",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="submission",
            name="passed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="submission",
            name="percent",
            field=models.FloatField(default=0.0),
        ),
    ]
