# Generated by Django 4.2.28 on 2026-03-06 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_lessonmaterial_aianalysis"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lessonmaterial",
            old_name="pdf_file",
            new_name="file",
        ),
    ]
