# Generated by Django 4.2.28 on 2026-03-10 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_rename_pdf_file_lessonmaterial_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="requested_question_count",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="quiz",
            name="root_quiz",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="descendant_quizzes",
                to="students.quiz",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="attempt_no",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
