# Generated by Django 4.2.28 on 2026-03-10 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0007_quiz_requested_question_count_quiz_root_quiz_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="created_by",
        ),
    ]
