# Generated by Django 4.2.28 on 2026-03-10 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("students", "0009_quiz_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quizzes_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
