# Generated by Django 4.2.28 on 2026-03-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0010_quiz_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="can_access_platform",
            field=models.BooleanField(default=False),
        ),
    ]
