# Generated by Django 4.2.28 on 2026-03-25 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("students", "0011_student_can_access_platform"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="submission",
            options={"ordering": ["-submitted_at", "-created_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="submission",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="student",
            name="actual_performance",
        ),
        migrations.RemoveField(
            model_name="student",
            name="attendance",
        ),
        migrations.RemoveField(
            model_name="student",
            name="final",
        ),
        migrations.RemoveField(
            model_name="student",
            name="homework",
        ),
        migrations.RemoveField(
            model_name="student",
            name="midterm",
        ),
        migrations.AddField(
            model_name="submission",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="choice",
            name="text",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="lessonmaterial",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_quizzes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="quiz_type",
            field=models.CharField(
                choices=[("manual", "Manual"), ("ai", "AI"), ("remedial", "Remedial")],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="student",
            name="group",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="submission",
            name="max_score",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="submission",
            name="score",
            field=models.FloatField(default=0),
        ),
        migrations.RemoveField(
            model_name="submission",
            name="started_at",
        ),
    ]
